# Generic bootloader Makefile - ONE file for every chip/family (2026-08-05,
# replaces the per-chip Makefile.bsl_STM32xxx copies, which only ever
# differed by 4 mechanically-derivable values). PROCESSOR is passed on the
# make command line - normally by etc/gen_bsl_boundary.sh:
#
#   make -f Makefile.bsl PROCESSOR=STM32G030K6
#
# FAMILY, BOARD and the startup file are all derived from it below, so a new
# chip needs NO new file here - only its .ld template in etc/ld (usually
# already covered by the package-less reference library) and, for G0, its
# startup file in etc/startup (shared per subfamily).
#
# BOARD is the family-wide fixed default, same rule as the apps (one default
# per family, never per-chip board conditionals): MBHP_DIPCOREF4 for all
# F4xx, STM32G0GENERIC for all G0xx. No live code branches on a per-chip
# BOARD define (verified 2026-08-05) - it only feeds MIOS32_BOARD_STR and
# the board pin tables in mios32_board.c.

ifeq ($(PROCESSOR),)
$(error PROCESSOR must be given, e.g. "make -f Makefile.bsl PROCESSOR=STM32G030K6" - normally this Makefile is invoked by etc/gen_bsl_boundary.sh)
endif

ifeq ($(findstring STM32F4,$(PROCESSOR)),STM32F4)
FAMILY    = 	STM32F4xx
BOARD	  = 	MBHP_DIPCOREF4
# single canonical startup shared by the whole F4xx family (see the same
# rule and rationale in programming_models/traditional/programming_model.mk)
STARTUP_FILE = $(MIOS32_PATH)/etc/startup/STM32F4xx/startup_stm32f4xx.c
else
FAMILY    = 	STM32G0xx
BOARD	  = 	STM32G0GENERIC
# per-subfamily startup: startup_<lowercased 9-char line prefix>.c - same
# derivation as programming_model.mk (every chip in a subfamily shares the
# exact same vector table, regardless of package/density)
STARTUP_FILE = $(MIOS32_PATH)/etc/startup/STM32G0xx/startup_$(shell echo $(PROCESSOR) | cut -c1-9 | tr '[:upper:]' '[:lower:]').c
endif

LCD       =     dummy


################################################################################
# Source Files, include paths and libraries
################################################################################

THUMB_SOURCE    = $(STARTUP_FILE) \
				main.c \
				bsl_sysex.c

# (following source stubs not relevant for Cortex M0+/M4 derivatives)
THUMB_AS_SOURCE =
ARM_SOURCE      =
ARM_AS_SOURCE   =

C_INCLUDE = 	-I .
A_INCLUDE = 	-I .

LIBS =


################################################################################
# Remaining variables
################################################################################

# generated by etc/gen_bsl_boundary.sh on every build, fixed name so
# switching chips overwrites rather than accumulates copies, inside
# project_build/ so it stays with the rest of this build's generated
# output rather than cluttering this source directory (see that script's
# header comment)
LD_FILE   = 	project_build/cpu_bsl.ld
PROJECT   = 	project

DEBUG     =	-g
OPTIMIZE  =	-Os

CFLAGS =	$(DEBUG) $(OPTIMIZE)


################################################################################
# Include source modules via additional makefiles
################################################################################

# add MIOS32 sources
include $(MIOS32_PATH)/mios32/mios32.mk

# common make rules
include $(MIOS32_PATH)/include/makefile/common.mk
