# $Id: Makefile.bsl_MBHP_CORE_STM32 562 2009-05-22 22:35:29Z tk $

################################################################################
# following setup is static for DIPCOREF4 module
################################################################################

PROCESSOR =		STM32G030K6
FAMILY    = 	STM32G0xx
BOARD	  = 	STM32G030K6
LCD       =     dummy

################################################################################
# Source Files, include paths and libraries
################################################################################

THUMB_SOURCE    = startup_stm32g030.c \
				main.c \
				bsl_sysex.c

# (following source stubs not relevant for Cortex M0+ derivatives)
THUMB_AS_SOURCE =
ARM_SOURCE      =
ARM_AS_SOURCE   =

C_INCLUDE = 	-I .
A_INCLUDE = 	-I .

LIBS =


################################################################################
# Remaining variables
################################################################################

#LD_FILE   = 	$(MIOS32_PATH)/etc/ld/$(FAMILY)/$(PROCESSOR).ld
# specified when this makefile is executed from Makefile
LD_FILE   = 	STM32G030_bsl.ld
PROJECT   = 	project

DEBUG     =	-g
OPTIMIZE  =	-Os

CFLAGS =	$(DEBUG) $(OPTIMIZE)


################################################################################
# Include source modules via additional makefiles
################################################################################

# add MIOS32 sources
include $(MIOS32_PATH)/mios32/mios32.mk

# common make rules
include $(MIOS32_PATH)/include/makefile/common.mk
